Repository francoisbaudouin/LaZone, pull requests merged in 2023-02, with the labels that each got.

#36 [ADD] choose action and reaction
  flutter_application/assets/images/Microsoft-Teams-Symbole.jpg
  flutter_application/assets/images/i.jpg
  flutter_application/assets/images/logo-twitter.jpg
  flutter_application/lib/Logs/sign_in_tools.dart
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_action_github.dart
  flutter_application/lib/ServicePage/choose_action_planner.dart
  flutter_application/lib/ServicePage/choose_action_trello.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_discord.dart
  flutter_application/lib/ServicePage/choose_reaction_teams.dart
  flutter_application/lib/ServicePage/choose_reaction_twitter.dart
  flutter_application/lib/ServicePage/create_cards.dart
  flutter_application/lib/ServicePage/github_page.dart
  flutter_application/lib/ServicePage/planner_page.dart
  flutter_application/lib/ServicePage/reaction_service_page.dart
  flutter_application/lib/ServicePage/trello_page.dart
  flutter_application/lib/Tools/color.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/lib/home_page.dart
  flutter_application/lib/main.dart
  flutter_application/lib/profile_page.dart
  flutter_application/pubspec.yaml
Labels: Front

#39 Devops/27 create access to provide android version of mobile client
  docker-compose.yml
  flutter_application/Dockerfilemobile
  flutter_application/Dockerfileweb
  flutter_application/android/app/build.gradle
  flutter_application/lib/Logs/sign_in_page.dart
  flutter_application/lib/Logs/sign_in_tools.dart
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/home_page.dart
  flutter_application/lib/main.dart
  flutter_application/pubspec.yaml
  flutter_application/server-py.sh
  flutter_application/windows/flutter/generated_plugin_registrant.cc
  flutter_application/windows/flutter/generated_plugins.cmake
  server/yarn.lock
Labels: Docker, DevOps

#40 Fullstack/38 link front actions reactions card to back areas
  .gitignore
  flutter_application/.gitignore
  flutter_application/lib/Logs/sign_in_tools.dart
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_action_github.dart
  flutter_application/lib/ServicePage/choose_action_planner.dart
  flutter_application/lib/ServicePage/choose_action_trello.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_discord.dart
  flutter_application/lib/ServicePage/choose_reaction_teams.dart
  flutter_application/lib/ServicePage/choose_reaction_twitter.dart
  flutter_application/lib/ServicePage/confirm_area_page.dart
  flutter_application/lib/ServicePage/reaction_service_page.dart
  flutter_application/lib/Tools/color.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/lib/home_page.dart
  flutter_application/lib/profile_page.dart
  flutter_application/package.json
  server/.gitignore
  server/api/controllers/actions.js
  server/api/controllers/areas.js
  server/api/controllers/reactions.js
  server/api/controllers/services.js
  server/api/controllers/tokens.js
  server/api/controllers/users.js
  server/api/passport/local.js
  server/api/prisma/schema.prisma
  server/api/routes/actions.js
  server/api/routes/areas.js
  server/api/routes/reactions.js
  server/api/routes/services.js
  server/api/routes/tokens.js
  server/api/routes/users.js
  server/api/utils/basicConfig.js
  server/db/schema.sql
  server/dockerfile
  server/index.js
  server/package.json
  server/services/action/githubAction.js
  server/services/reaction/discordClient.js
  server/services/reaction/discordEmbeds/discordEmbeds.js
  server/services/reaction/discordReaction.js
  server/services/servicesManager.js
Labels: Front, Back-end

#42 [UPDATE]: readme and add notion
  README.md
Labels: documentation

#45 [ADD] new pass to choose the area
  flutter_application/lib/ServicePage/choose_action_github.dart
  flutter_application/lib/ServicePage/choose_action_planner.dart
  flutter_application/lib/ServicePage/choose_action_trello.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_discord.dart
  flutter_application/lib/ServicePage/choose_reaction_teams.dart
  flutter_application/lib/ServicePage/choose_reaction_twitter.dart
  flutter_application/lib/ServicePage/confirm_area_page.dart
  flutter_application/lib/ServicePage/reaction_service_page.dart
Labels: Front

#46 [ADD]: reusable function to access datas from database
  .gitignore
  server/api/controllers/actions.js
  server/api/controllers/areas.js
  server/api/controllers/reactions.js
  server/api/controllers/services.js
  server/api/controllers/tokens.js
  server/api/controllers/users.js
  server/api/routes/actions.js
  server/api/routes/areas.js
  server/api/routes/reactions.js
  server/api/routes/services.js
  server/api/routes/tokens.js
  server/api/routes/users.js
  server/api/utils/basicConfig.js
  server/index.js
  server/services/reaction/discordClient.js
  server/services/servicesManager.js
Labels: Back-end

#51 [ADD] dark heroic fantasy theme in home page
  flutter_application/assets/fonts/Ancient_Medium.ttf
  flutter_application/assets/fonts/OldLondon.ttf
  flutter_application/assets/images/Microsoft-Teams-Symbole.jpg
  flutter_application/assets/images/Microsoft-Teams-Symbole.png
  flutter_application/assets/images/Planner-logo.jpg
  flutter_application/assets/images/Planner-logo.png
  flutter_application/assets/images/Trello-Symbole.jpg
  flutter_application/assets/images/Trello-Symbole.png
  flutter_application/assets/images/discord-logo.png
  flutter_application/assets/images/f.jpg
  flutter_application/assets/images/font.jpg
  flutter_application/assets/images/github-logo.png
  flutter_application/assets/images/i.jpg
  flutter_application/assets/images/logo-twitter.jpg
  flutter_application/assets/images/logo-twitter.png
  flutter_application/assets/images/microsoft-teams-logo.jpg
  flutter_application/assets/images/parchemin.png
  flutter_application/assets/images/parchemin2.png
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_action_github.dart
  flutter_application/lib/ServicePage/choose_action_planner.dart
  flutter_application/lib/ServicePage/choose_action_trello.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_discord.dart
  flutter_application/lib/ServicePage/choose_reaction_teams.dart
  flutter_application/lib/ServicePage/choose_reaction_twitter.dart
  flutter_application/lib/ServicePage/confirm_area_page.dart
  flutter_application/lib/ServicePage/create_cards.dart
  flutter_application/lib/ServicePage/reaction_service_page.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/setup_page.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/lib/Tools/title_cards.dart
  flutter_application/lib/home_page.dart
  flutter_application/lib/main.dart
  flutter_application/lib/profile_page.dart
  flutter_application/pubspec.yaml
Labels: Front

#54 Front end/53 add the theme to all categories
  flutter_application/assets/images/button.jpg
  flutter_application/assets/images/f.jpg
  flutter_application/assets/images/font_menu.jpg
  flutter_application/lib/Logs/sign_in_page.dart
  flutter_application/lib/Logs/sign_in_tools.dart
  flutter_application/lib/Logs/sign_up_page.dart
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/Tools/color.dart
  flutter_application/lib/Tools/setup_page.dart
  flutter_application/lib/home_page.dart
  flutter_application/lib/main.dart
  flutter_application/lib/profile_page.dart
  flutter_application/pubspec.yaml
Labels: Front

#57 [ADD] services page
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/home_page.dart
Labels: Front

#60 Full stack/29 link back oauth to front oauht
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/package.json
  flutter_application/pubspec.yaml
  server/Dockerfile
  server/api/passport/discord.js
  server/api/passport/git.js
  server/api/passport/local.js
  server/api/routes/auth/discord_auth.js
  server/api/routes/auth/git_auth.js
  server/api/routes/auth/local_auth.js
  server/api/utils/authorization.js
  server/api/utils/basicConfig.js
  server/index.js
  server/package.json
  server/services/reaction/discordClient.js
Labels: Front, Back-end

#63 [UPDATE]: add 'identify' scope for discord strategy used by passport
  server/api/passport/discord.js
  server/api/routes/auth/discord_auth.js
Labels: Back-end

#37 Organise docker secret
  .dart_tool/package_config.json
  .dart_tool/package_config_subset
  .dart_tool/version
  .gitignore
  docker-compose.yml
  flutter_application/mobile.Dockerfile
  flutter_application/web.Dockerfile
  server/db/Dockerfile
Labels: DevOps, Database

#66 [ADD]: Twitter Reaction
  server/Dockerfile
  server/api/controllers/users.js
  server/api/utils/basicConfig.js
  server/package.json
  server/services/reaction/twitterReaction.js
  server/services/servicesManager.js
Labels: Back-end

#65 Front end/55 add service serction
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/reaction_service_page.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/color.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/lib/home_page.dart
Labels: Front

#70 Frontend/67 implement server address selection in login and signup page
  flutter_application/lib/Logs/sign_in_page.dart
  flutter_application/lib/Logs/sign_in_tools.dart
  flutter_application/lib/Logs/sign_up_page.dart
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/global.dart
  flutter_application/lib/main.dart
Labels: Front

#71 [ADD] id to all action and reaction
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/Tools/text.dart
Labels: Front

#74 [ADD] logo and name to the project
  flutter_application/assets/images/logo.png
  flutter_application/lib/main.dart
  flutter_application/pubspec.yaml
  flutter_application/web/index.html
  flutter_application/web/logo.png
  flutter_application/web/manifest.json
Labels: Front

#78 Fullstack/73 handle about.json route
  flutter_application/android/app/src/main/AndroidManifest.xml
  flutter_application/lib/home_page.dart
  server/index.js
Labels: Front, Back-end

#77 Front end/75 change trello to youtube
  flutter_application/assets/images/Trello-Symbole.png
  flutter_application/assets/images/Youtube-Symbole.png
  flutter_application/assets/images/font-overlay.png
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_action_youtube.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/color.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/lib/home_page.dart
  flutter_application/lib/profile_page.dart
  flutter_application/pubspec.yaml
Labels: Front

#80 [ADD] profil information and reorgarnisation of the home page
  flutter_application/assets/images/Microsoft-Teams-Symbole.png
  flutter_application/assets/images/discord-logo.png
  flutter_application/assets/images/logo-twitter.png
  flutter_application/assets/images/nothing.png
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/setup_page.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/lib/home_page.dart
  flutter_application/lib/profile_page.dart
  flutter_application/pubspec.yaml
Labels: Front
