Repository francoisbaudouin/LaZone, pull requests merged in 2023-03, with the labels that each got.

#85 [ADD] display all area and push in json list
  flutter_application/assets/images/nothing.png
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/area_page.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/global.dart
  flutter_application/lib/Tools/setup_page.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/lib/home_page.dart
Labels: Front

#87 facebook service
  flutter_application/assets/images/Facebook-logo.png
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/area_page.dart
  flutter_application/lib/ServicePage/choose_action_facebook.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/color.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/pubspec.yaml
Labels: Front

#89 Frontend/82 enable oauth2 on mobile client
  flutter_application/android/app/src/main/AndroidManifest.xml
  flutter_application/lib/Logs/sign_in_page.dart
  flutter_application/lib/Logs/sign_in_tools.dart
  flutter_application/lib/Logs/sign_up_page.dart
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/global.dart
Labels: Front

#94 Fullstack/91 notify the user when an account already exists
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/home_page.dart
  server/api/routes/auth/local_auth.js
Labels: Front, Back-end

#92 Select server and channel from json
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/ServicePage/choose_action_github.dart
  flutter_application/lib/ServicePage/choose_reaction_discord.dart
  flutter_application/lib/ServicePage/choose_reaction_teams.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/global.dart
  flutter_application/lib/Tools/setup_page.dart
  flutter_application/lib/Tools/text.dart
Labels: Front

#95 change teams to reddit
  flutter_application/assets/images/Reddit-Logo.png
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/area_page.dart
  flutter_application/lib/ServicePage/choose_action_reddit.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_reddit.dart
  flutter_application/lib/ServicePage/reaction_service_page.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/color.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/global.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/pubspec.yaml
  flutter_application/web/manifest.json
Labels: Front

#98 [FIX] login responsive and crop image
  flutter_application/assets/images/font-overlay.png
  flutter_application/assets/images/font_menu.jpg
  flutter_application/lib/Logs/sign_in_page.dart
  flutter_application/lib/Logs/sign_in_tools.dart
  flutter_application/lib/Logs/sign_up_page.dart
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/setup_page.dart
  flutter_application/lib/home_page.dart
  flutter_application/lib/profile_page.dart
  flutter_application/pubspec.yaml
Labels: Front

#103 Front end/100 adapt images of services
  flutter_application/analysis_options.yaml
  flutter_application/assets/images/Facebook-logo.png
  flutter_application/assets/images/Microsoft-Teams-Symbole.png
  flutter_application/assets/images/Planner-logo.png
  flutter_application/assets/images/Reddit-Logo.png
  flutter_application/assets/images/Youtube-Symbole.png
  flutter_application/assets/images/discord-logo.png
  flutter_application/assets/images/github-logo.png
  flutter_application/assets/images/logo-discord.png
  flutter_application/assets/images/logo-twitter.png
  flutter_application/assets/images/nothing.png
  flutter_application/assets/images/twitter-logo.png
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/area_page.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_discord.dart
  flutter_application/lib/ServicePage/choose_reaction_twitter.dart
  flutter_application/lib/ServicePage/reaction_service_page.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/setup_page.dart
  flutter_application/lib/home_page.dart
  flutter_application/pubspec.yaml
Labels: Front

#105 Front end/104 add all id of all actions and reactions
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_action_facebook.dart
  flutter_application/lib/ServicePage/choose_action_youtube.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_reddit.dart
  flutter_application/lib/ServicePage/confirm_area_page.dart
  flutter_application/lib/Tools/create_cards.dart
Labels: Front

#107 Youtube reaction
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_youtube.dart
  flutter_application/lib/ServicePage/reaction_service_page.dart
Labels: Front

#108 Backend/90 send action and reaction parameters to client
  flutter_application/lib/ServicePage/services_page.dart
  server/Dockerfile
  server/api/controllers/services.js
  server/api/controllers/users.js
  server/api/routes/auth/discord_auth.js
  server/api/routes/services.js
  server/api/utils/basicConfig.js
  server/package.json
  server/services/servicesInitialisation.js
  server/services/servicesManager.js
Labels: Back-end

#111 Frontend/99 handle users areas display
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/home_page.dart
  flutter_application/pubspec.yaml
  server/api/controllers/areas.js
  server/api/controllers/users.js
  server/index.js
  server/services/action/githubAction.js
  server/services/reaction/twitterReaction.js
  server/services/servicesManager.js
Labels: Front, Back-end

#112 Front end/109 display of maximum area per line
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_reddit.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/global.dart
  flutter_application/lib/home_page.dart
Labels: Front

#113 Add good id to tweeter reaction
  flutter_application/lib/ServicePage/choose_action_github.dart
  flutter_application/lib/ServicePage/choose_page.dart
Labels: Front

#114 Backend/81 implement facebook service action
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/windows/flutter/generated_plugin_registrant.cc
  server/Dockerfile
  server/api/passport/facebook.js
  server/api/routes/auth/facebook_auth.js
  server/api/utils/basicConfig.js
  server/index.js
  server/services/action/facebookAction.js
  server/services/action/githubAction.js
  server/services/reaction/discordClient.js
  server/services/reaction/discordEmbeds/discordEmbeds.js
  server/services/reaction/parser/dataParser.js
  server/services/servicesManager.js
Labels: Back-end

#115 Backend/76 youtube action implementation
  flutter_application/windows/flutter/generated_plugin_registrant.cc
  flutter_application/windows/flutter/generated_plugins.cmake
  server/Dockerfile
  server/api/prisma/schema.prisma
  server/api/routes/auth/google_auth.js
  server/api/utils/basicConfig.js
  server/package.json
  server/services/action/youtubeAction.js
  server/services/reaction/discordEmbeds/discordEmbeds.js
  server/services/reaction/parser/dataParser.js
  server/services/servicesManager.js
Labels: Back-end

#116 Backend/101 implement reddit actionreaction
  server/api/utils/basicConfig.js
  server/index.js
  server/services/action/githubAction.js
  server/services/action/redditAction.js
  server/services/reaction/discordClient.js
  server/services/reaction/discordEmbeds/discordEmbeds.js
  server/services/reaction/discordReaction.js
  server/services/reaction/parser/dataParser.js
  server/services/reaction/redditReaction.js
  server/services/servicesManager.js
Labels: Back-end

#125 Fullstack/97 retrieve services actions and reactions parameters from server
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/ServicePage/choose_action_github.dart
  flutter_application/lib/ServicePage/choose_action_reddit.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_reddit.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/global.dart
  flutter_application/lib/Tools/setup_page.dart
  server/Dockerfile
  server/api/controllers/services.js
  server/api/controllers/users.js
  server/api/routes/auth/reddit_auth.js
  server/services/servicesInitialisation.js
  server/services/servicesManager.js
Labels: Front, Back-end

#127 Front end/123 fix responsive design
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/profile_page.dart
Labels: Front

#121 [UPDATE]; markdown better
  README.md
  flutter_application/windows/flutter/generated_plugin_registrant.cc
Labels: documentation

#129 Backend/126 add discord reaction back
  flutter_application/lib/ServicePage/choose_page.dart
  server/api/utils/basicConfig.js
  server/package.json
  server/services/reaction/discordReaction.js
  server/services/servicesManager.js
Labels: Back-end

#128 add about.json and remove some routes
  server/about.json
Labels: documentation

#131 Backend/117 login by oauth2 identification
  flutter_application/lib/Logs/sign_in_page.dart
  flutter_application/lib/Logs/sign_in_tools.dart
  flutter_application/lib/ServicePage/choose_reaction_discord.dart
  server/Dockerfile
  server/api/passport/google.js
  server/api/passport/local.js
  server/api/passport/microsoft.js
  server/api/prisma/schema.prisma
  server/api/routes/auth/microsoft_auth.js
  server/db/schema.sql
  server/index.js
  server/services/reaction/discordReaction.js
  server/services/reaction/twitterReaction.js
Labels: Back-end

#134 [ADD]: new routes delete area
  server/api/controllers/areas.js
  server/api/routes/areas.js
Labels: Back-end

#132 Front end/130 add discord mp reaction
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/choose_reaction_discord.dart
  flutter_application/lib/ServicePage/choose_reaction_youtube.dart
  flutter_application/lib/ServicePage/reaction_service_page.dart
Labels: Front

#137 [UPDATE]: emergency mobile fix
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_action_github.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/ServicePage/services_page.dart
  flutter_application/lib/Tools/create_cards.dart
  flutter_application/lib/Tools/global.dart
  flutter_application/lib/Tools/setup_page.dart
  flutter_application/lib/home_page.dart
Labels: Front

#138 update doc
  README.md
Labels: documentation

#139 Fullstack/135 delete areas from front button
  flutter_application/lib/ServicePage/action_reaction_page.dart
  flutter_application/lib/ServicePage/choose_page.dart
  flutter_application/lib/home_page.dart
  server/api/controllers/areas.js
  server/api/routes/areas.js
  server/index.js
Labels: Front, Back-end
