Repository francoisbaudouin/LaZone, pull requests merged in 2023-01, with the labels that each got.

#5 build docker server
  package.json
  pubspec.lock
  pubspec.yaml
  server/dockerfile
  server/index.js
  server/package-lock.json
  server/package.json
Labels: Docker, DevOps

#6 Back end/4 back end folder basic architecture
  .gitignore
  package-lock.json
  package.json
  server/api/config/config.js
  server/api/controllers/users.controllers.js
  server/api/prisma.models/users.model.js
  server/api/routes/users.routes.js
  server/index.js
Labels: Docker, DevOps, Back-end

#12 Fullstack/8 retrieve datas from database with button
  .gitignore
  flutter_application/lib/main.dart
  flutter_application/pubspec.lock
  flutter_application/pubspec.yaml
  server/about.json
  server/index.js
Labels: Front, Back-end

#15 [ADD] sign up page and clean code of sign in page
  flutter_application/lib/home_page.dart
  flutter_application/lib/login_page.dart
  flutter_application/lib/main.dart
  flutter_application/lib/navigate_bar.dart
  flutter_application/lib/sign_in_page.dart
  flutter_application/lib/sign_up_page.dart
  flutter_application/lib/tools/sign_in_tools.dart
  flutter_application/lib/tools/sign_up_tools.dart
Labels: Front

#17 build docker db
  docker-compose.yml
  flutter_application/Dockerfilemobile
  server/db/Dockerfile
  server/db/user_privileges.sql
  server/dockerfile
Labels: Docker, DevOps

#22 Back end/9 start rest api with signup and sign in features
  docker-compose.yml
  flutter_application/Dockerfilemobile
  package-lock.json
  package.json
  server/.gitignore
  server/api/.gitignore
  server/api/passport/jwt.js
  server/api/passport/local.js
  server/api/prisma.models/users.model.js
  server/api/prisma/schema.prisma
  server/api/routes/auth.routes.js
  server/api/utils/authorization.js
  server/api/utils/utils.js
  server/db/Dockerfile
  server/db/schema.sql
  server/db/user_privileges.sql
  server/dockerfile
  server/index.js
  server/package-lock.json
  server/package.json
  server/yarn.lock
Labels: Docker, Back-end, Database

#25 [UPDATE]: link front with back for login/signup system
  flutter_application/lib/discord_page.dart
  flutter_application/lib/sign_in_page.dart
  flutter_application/lib/sign_up_page.dart
  flutter_application/lib/tools/sign_in_tools.dart
  flutter_application/lib/tools/sign_up_tools.dart
  server/api/routes/auth.routes.js
  server/index.js
Labels: Front, Back-end

#28 Backend/24 login to services with oauth2
  server/api/controllers/users.controllers.js
  server/api/passport/discord.js
  server/api/passport/git.js
  server/api/passport/jwt.js
  server/api/routes/auth/discord_auth.js
  server/api/routes/auth/git_auth.js
  server/api/routes/auth/local_auth.js
  server/api/routes/users.routes.js
  server/api/utils/authorization.js
  server/dockerfile
  server/index.js
  server/package.json
  server/yarn.lock
Labels: Back-end

#21 Home Page with button connection service && Check e-mail format
  flutter_application/assets/fonts/product_sans_bold.ttf
  flutter_application/assets/fonts/product_sans_bold_italic.ttf
  flutter_application/assets/fonts/product_sans_italic.ttf
  flutter_application/assets/fonts/product_sans_regular.ttf
  flutter_application/assets/fonts/roboto_bold.ttf
  flutter_application/assets/fonts/roboto_italic.ttf
  flutter_application/assets/fonts/roboto_regular.ttf
  flutter_application/assets/images/Planner-logo.jpg
  flutter_application/assets/images/Trello-Symbole.jpg
  flutter_application/assets/images/discord-logo.png
  flutter_application/assets/images/github-logo.png
  flutter_application/assets/images/google_logo.png
  flutter_application/assets/images/microsoft-teams-logo.jpg
  flutter_application/lib/Logs/sign_in_page.dart
  flutter_application/lib/Logs/sign_in_tools.dart
  flutter_application/lib/Logs/sign_up_page.dart
  flutter_application/lib/Logs/sign_up_tools.dart
  flutter_application/lib/ServicePage/create_cards.dart
  flutter_application/lib/ServicePage/github_page.dart
  flutter_application/lib/ServicePage/planner_page.dart
  flutter_application/lib/ServicePage/trello_page.dart
  flutter_application/lib/Tools/color.dart
  flutter_application/lib/Tools/text.dart
  flutter_application/lib/discord_page.dart
  flutter_application/lib/home_page.dart
  flutter_application/lib/main.dart
  flutter_application/lib/navigate_bar.dart
  flutter_application/pubspec.lock
  flutter_application/pubspec.yaml
  flutter_application/windows/flutter/generated_plugin_registrant.cc
  flutter_application/windows/flutter/generated_plugins.cmake
Labels: Front

#32 [ADD] button download to get mobile apps
  flutter_application/lib/home_page.dart
Labels: Front
